### ISSUE TITLE
Command parsing should be reworked

### ISSUE THREAD

**Issue by rm-you** [jamesjamail/TunnelQuestBot#12]
The structure of the current commands is possibly not ideal:

* No real need to require a semicolon or commas
* Verbs could be more consistent (currently add/end, which is a mix of add/remove and begin/end)
* Personal preference is to start with the noun rather than the verb (avoids pluralization changes), but either is technically fine

A full proposal should be discussed and agreed upon, but maybe something like this? Hopefully not forgetting anything:

```
!help
!watch <add|create|start|begin> <server> <item>
!watch <remove|delete|stop|end> <server> <item>
!watch list
!watch show <server> <item>
!watch extend <server> <item>
!watch extend all
```

Implementation can be done cleanly for this using regular expressions.

**Comment by jamesjamail** [comment]
I like your proposal.  Maybe this is something we can share on the Discord server and people can vote on.

One thing to keep in mind is that users have requested to watch WTB messages as well as WTS.  If this a future feature we plan to implement (I'd like to once we get some of the easier tickets completed), we should plan accordingly with the command structure.

Another AuctionBot watched both WTB and WTS, and you would enter commands like 'WTB a ruby 2000' which I found very confusing because as a new user I wasnt sure if that was watching for 'wtb a ruby' or me saying 'wtb a ruby'.  So let's not do that.

Since people who are wanting to add watched for WTB messages are the minority, I think it should be an optional argument so average users don't need to worry about it.

**Comment by rm-you** [comment]
I don't like `watch extend all`... It's inconsistent with `watch show` / `watch list` because instead of changing the verb, it uses a second arg. I'm just not sure what to do about that.

For WTB/WTS, maybe we have it default to scanning everything, and allow people to be specific if they want by adding an optional arg for it?
If we add the new arg *before* the server arg, it would break it up a bit and hopefully make the meaning clear. It complicates the code a little to have an optional arg BEFORE the required args, but it shouldn't be too bad given that both the optional arg and the server arg must be one of a few static values.
```
!watch add|create|start|begin [wtb|wts] <server> <item>
!watch remove|delete|stop|end [wtb|wts] <server> <item>
!watch show [wtb|wts] <server> <item>
!watch extend [wtb|wts] <server> <item>
```

Ah, and maybe we should allow filtering for a specific server (or wtb/wts, per above) on a `watch list`?
```
!watch list [wtb|wts] [<server>]
```

**Comment by rm-you** [comment]
This is handled in https://github.com/jamesjamail/TunnelQuestBot/tree/tsc_prisma_refactor
